image:
  repository: ""
  tag: "latest"
replicaCount: 1
appEnv:
  SPRING_PROFILES_ACTIVE: "postgres"
  RETAIL_IDENTITY_DB_ENDPOINT: "postgres-identity:5432"
  RETAIL_IDENTITY_DB_NAME: "identitydb"
  RETAIL_IDENTITY_DB_USER: "identity_user"
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
