server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: identity-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:mem:identitydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    com.retailstore: INFO
retail:
  identity:
    jwt:
      secret: ${RETAIL_IDENTITY_JWT_SECRET:bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXlteXN1cGVyc2VjcmV0a2V5bXlzdXBlcg==}
      expiration-ms: ${RETAIL_IDENTITY_JWT_EXPIRATION_MS:86400000}
