server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/retailstore/protocol/openid-connect/certs}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    com.retailstore: INFO
retail:
  order:
    messaging:
      enabled: ${RETAIL_ORDER_MESSAGING_ENABLED:false}
      sqs:
        queue-url: ${RETAIL_ORDER_MESSAGING_SQS_QUEUE_URL:}
