# Prod profile — EKS service mesh + EKS Keycloak.
# Swagger disabled. Health details hidden.

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}

retail:
  experience:
    keycloak:
      token-uri: ${KEYCLOAK_TOKEN_URI}
      client-id: ${KEYCLOAK_CLIENT_ID:experience-service}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
    endpoints:
      catalog: ${RETAIL_EXPERIENCE_ENDPOINTS_CATALOG}
      carts:   ${RETAIL_EXPERIENCE_ENDPOINTS_CARTS}
      orders:  ${RETAIL_EXPERIENCE_ENDPOINTS_ORDERS}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  tracing:
    sampling:
      probability: 0.05
  zipkin:
    tracing:
      endpoint: ${TRACING_ENDPOINT}
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.retailstore: WARN
    reactor.netty: ERROR
