{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.fullname" . }}
  labels: {{- include "orders.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.appEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
