image:
  repository: "host.docker.internal:5000/retailstore/carts"
  tag: "local"
  pullPolicy: IfNotPresent
replicaCount: 1
appEnv:
  SPRING_PROFILES_ACTIVE: "local"
  RETAIL_CART_DYNAMODB_TABLE_NAME: "Carts"
  RETAIL_CART_DYNAMODB_ENDPOINT:   "http://dynamodb-local:8000"
  AWS_ACCESS_KEY_ID:     "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  AWS_REGION:            "us-east-1"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8180"
  ZIPKIN_HOST:   "zipkin"
resources:
  limits:
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
