image:
  repository: "host.docker.internal:5000/retailstore/catalog"
  tag: "local"
  pullPolicy: IfNotPresent
replicaCount: 1
appEnv:
  SPRING_PROFILES_ACTIVE: "local"
  MYSQL_HOST:     "mysql"
  MYSQL_PORT:     "3306"
  MYSQL_USER:     "catalog_user"
  MYSQL_PASSWORD: "catalog_pass"
  REDIS_HOST:     "redis-master"
  REDIS_PORT:     "6379"
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: "jpa"
  KEYCLOAK_HOST:  "keycloak"
  KEYCLOAK_PORT:  "8180"
  ZIPKIN_HOST:    "zipkin"
resources:
  limits:
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
