image:
  repository: "067744548987.dkr.ecr.us-east-1.amazonaws.com/retailstore/orders"
  tag: "local"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-pull-secret
replicaCount: 1
appEnv:
  SPRING_PROFILES_ACTIVE: "local"
  MYSQL_HOST:     "mysql"
  MYSQL_PORT:     "3306"
  MYSQL_USER:     "orders_user"
  MYSQL_PASSWORD: "orders_pass"
  RETAIL_ORDER_MESSAGING_ENABLED:      "true"
  KAFKA_BOOTSTRAP_SERVERS:             "kafka:9092"
  RETAIL_ORDER_MESSAGING_KAFKA_TOPIC:  "order-events-local"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8180"
  ZIPKIN_HOST:   "zipkin"
resources:
  limits:
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
